name: xtoolbox
description: "A toolbox full of Windows 10/11 utilities."
publish_to: 'none'

version: 5.0.0

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.5.3
  system_theme: ^3.1.2
  provider: ^6.1.5+1
  dynamic_color: ^1.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true